### ISSUE TITLE
Slack notification im Fall von update-Problemen

### ISSUE THREAD

**Issue by wlbr** [PlanetKiF/csgo#10]
Im Fall von Fehlern beim Update (sei es beim Updatescript selber oder beim Rückschreiben der botprofile.db) soll eine Nachricht an den Slack Channel 'server' geschickt werden. 

Wenn die letzten Zeilen des Logfiles anhängen würden wäre das doppelt schön (`tail updatelog.txt`)

Ggf. kann der gleiche Slack-Hook wir für die Github-Commits genutzt werden (dann mit Curl von der Shell aus), dazu müsste @oechslein die Rechte am Slack-Webhook prüfen und für den active-Clan aufmachen.

**Comment by oechslein** [comment]
Ich kann da die Rechte nicht mehr ändern:
![image](https://user-images.githubusercontent.com/6616171/107043385-3a571000-67c3-11eb-9451-bb0247002ae7.png)

Das Problem wird die Auth sein, der Webhook ist speziell für Github. Den Webhook selbst siehst Du ja in der Github Action.

**Comment by oechslein** [comment]
secrets.SLACK_WEBHOOK_URL habe ich mir nicht gesichert. Ich würde dafür einen neuen Webhok anlegen.
![image](https://user-images.githubusercontent.com/6616171/107043909-e6006000-67c3-11eb-961b-b1781aafc0aa.png)

**Comment by oechslein** [comment]
Ich habe nur gerade null Zeit.

**Comment by wlbr** [comment]
Läuft.
(Glaube ich und werden wir erst im Fehlerfall sehen. :-) )
