### ISSUE TITLE
Map Aliasse / Map Change fixen

### ISSUE THREAD

**Issue by CiskeB** [PlanetKiF/csgo#8]
In einigen Fällen hat der Map Change per Change Level nicht funktioniert - lag es an den Maps?

Prüfen: sind die Aliasse für den Map Change vorhanden und werden sie auch eingelesen?
"Diverse" gingen nicht
"Office" ging => das kann aber auch noch der alte Alias gewesen sein

**Comment by wlbr** [comment]
Die Aliase sind da und werden eingelesen. Beispielsweise ist auch einer für de_torntown.bsp da und ich erinnere mich, dass der gestern irgendwann nicht mehr ging. Auch den Befehl für de_port haben wir benutzt, der stand aber nicht in einer alten cfg.

meine Vermutung ist, dass der Server irgendwann in einem nicht definiertem Zustand war - nach welchem Fehler auch immer. Und dann gingen nicht mehr alle Befehle. Ich hatte schon mal Ähnliches, da hat er gar keine RCON Befehle mehr von mir angenommen.

Evtl. ist de_torntown.bsp kaputt und der Wechsel dahin ist die Ursache des gestrigen Problems gewesen.
Mag mal jemand einen Test machen, sich connecten und dann versuchen die Map zu laden?

Wenn hinter wieder was kaputt ist sollte ein `csctrl restart`in ssh genügen.

**Comment by wlbr** [comment]
Ich denk wir haben inzwischen gesehen, dass die Mapchange aliase nicht das Problem sind ...
