### ISSUE TITLE
Backup / Restorte von Dateien, die beim Update überschrieben werden

### ISSUE THREAD

**Issue by CiskeB** [PlanetKiF/csgo#9]
- botprofile.db
- weitere?
- 
Ansatz: Copy-Job nach Update Job via Crontab?

**Comment by wlbr** [comment]
Für botprofile.db resolved mit a464a3f694d3116696a884fe07aa2c893b27757a

Im Repo gibt es nun

- botprofile.db.custom. (Hierin liegen unsere eigenen Bots mit den unfassbar ~lustigen~ befriedigenden Namen)
- botprofile.db.lastorig (Dies ist ein Backupdatei der aktuellen "offiziellen" botprofile.db)

Nach dem Update wird nun das Script `cscheckbotfiles` aufgerufen. Dieses tut:

- wenn die botprofile.db == alte original-Datei ==> ersetzen der Originaldatei mit unseren Anpassungen (botprofile.db.custom)
- wenn die botprofile.db == unsere eigene Datei ist (botprofile.db.custom) ==> nix tun
- wenn die botprofile.db von beiden abweicht, dann hat das Update bzw. de Steam Upstream sie verändert ==> Meldung ins Logfile, keine Änderung ==> manueller Check notwendig.

Man könnte/sollte bei Meldungen ins Logfile (durch diesen Check oder durch das Update selber eine Meldung in Slack machen. (Nur im Problemfall). ==> Neues Ticket.

Wenn weitere Dateien überschrieben werden sollten (momentan fällt mir keine ein, da wir ansonsten nur offizielle Anpassungsfiles nutzen), dann müssen wir im Einzelfall dafür Lösungen bauen.
